---
- name: install docker
  hosts: ansible1
  become: true

  tasks:

    - name: update apt
      apt:
        update_cache: yes
        upgrade: "yes"

    - name: install docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes

    - name: add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: add docker repository
      apt_repository:
        filename: docker 
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
        state: present

    - name: install docker engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-scan-plugin
          - docker-compose-plugin
        update_cache: yes

    - name: Install pip3
      apt:
        name: python3-pip
        update_cache: yes
    
    - name: Install docker Python library
      pip:
        name: docker
        state: present

    - name: start the app
      docker_container:
        pull: yes
        recreate: yes
        name: weather-app
        state: started
        image: bensh99/weatherapp:latest
        exposed_ports: "8000"